# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

"""
Add date_log table

Create Date: 2017-07-12 10:49:24.148804
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2a76f0979e95'
down_revision = '436dc4cea0f3'


def upgrade():
  """Upgrade database schema and/or data, creating a new revision."""
  # commands auto generated by Alembic - please adjust! #
  op.create_table(
      'protocol',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.Column('resource_id', sa.Integer(), nullable=True),
      sa.Column('resource_type', sa.String(length=250), nullable=True),
      sa.Column('fact', sa.String(length=250), nullable=True),
      sa.Column('created_at', sa.DateTime(), nullable=True),
      sa.PrimaryKeyConstraint('id')
  )
  op.create_index('ix_resource',
                  'protocol',
                  ['resource_type', 'resource_id', 'fact'],
                  unique=False)
  # end Alembic commands #


def downgrade():
  """Downgrade database schema and/or data back to the previous revision."""
  # commands auto generated by Alembic - please adjust! #
  op.drop_index('ix_resource', table_name='protocol')
  op.drop_table('protocol')
  # end Alembic commands #
