# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

"""
new fields in acl

Create Date: 2018-07-19 12:57:15.233417
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd982f2b0f754'
down_revision = 'a884c7c1e0b3'


def upgrade():
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'propagated_access_control_roles',
        sa.Column('read', sa.Boolean(), nullable=False),
        sa.Column('update', sa.Boolean(), nullable=False),
        sa.Column('delete', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('for_path', sa.String(length=250), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('modified_by_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'],
                                ['access_control_roles.id'],
                                 ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_propagated_access_control_roles_updated_at',
                    'propagated_access_control_roles',
                    ['updated_at'],
                    unique=False)
    # ### end Alembic commands ###

def downgrade():
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_propagated_access_control_roles_updated_at',
                  table_name='propagated_access_control_roles')
    op.drop_table('propagated_access_control_roles')
    # ### end Alembic commands ###
