# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

"""
move permissions flags into acl

Create Date: 2018-07-24 09:53:01.687603
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a42b39df9779'
down_revision = '7cf263056858'


def upgrade():
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """update access_control_list as acl
           join access_control_roles as acr
           on acl.ac_role_id = acr.id
           set acl.read = acr.read,
               acl.update = acr.update,
               acl.delete = acr.delete
           where ac_role_id is not Null;"""
    )
    # ### end Alembic commands ###

def downgrade():
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
