# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

"""
add indexes in bucket_items

Create Date: 2018-07-21 19:32:40.912658
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '913f6da9cda8'
down_revision = 'fe902e3803aa'


def upgrade():
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_left_obj_path', 'bucket_items', ['left_obj_type', 'left_obj_id', 'path'], unique=False)
    op.create_index('ix_right_obj_path', 'bucket_items', ['right_obj_type', 'right_obj_id', 'path'], unique=False)
    op.drop_index('ix_right_obj', table_name='bucket_items')
    op.drop_index('left_obj_id', table_name='bucket_items')
    op.create_unique_constraint(None, 'bucket_items', ['left_obj_id', 'left_obj_type', 'right_obj_id', 'right_obj_type', 'parent_relationship_id', 'parent_bucket_id'])
    # ### end Alembic commands ###

def downgrade():
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucket_items', type_='unique')
    op.create_index('left_obj_id', 'bucket_items', ['left_obj_id', 'left_obj_type', 'right_obj_id', 'right_obj_type', 'parent_relationship_id', 'parent_bucket_id', 'path'], unique=True)
    op.create_index('ix_right_obj', 'bucket_items', ['right_obj_type', 'right_obj_id'], unique=False)
    op.drop_index('ix_right_obj_path', table_name='bucket_items')
    op.drop_index('ix_left_obj_path', table_name='bucket_items')
    # ### end Alembic commands ###
